---
title: "How I Met My Partner In Crime"
subtitle: "Comparing social behavior regarding partners selection in criminal and non-criminal populations"
date: "2023-11-09"
summary: Seeking a criminal partner is not unlike searching for a dance partner on a Saturday night. Despite our law-abiding inclinations, humans are inherently social creatures, driven by the innate need to connect with others. We interact with other people almost every day, forming a so-called "social network". Interestingly, regardless of the end goal - whether it is dancing or robbery - the mechanisms underlying these social connections have remarkable similarities.
image:
  caption: <i>Image is generated by DALL·E</i>
  focal_point: ""
  placement: 1
  preview_only: false
categories: ["Criminology"]
tags: ["Criminology", "Sociology"]
---

**Seeking a criminal partner is not unlike searching for a dance partner on a Saturday night. Despite our law-abiding inclinations, humans are inherently social creatures, driven by the innate need to connect with others. We interact with other people almost every day, forming a so-called "social network". Think about your close friends and try to remember why you became friends with them in the first place. Was it because you already had friends in common? Did they attract you because they shared the same interests? Or did they simply appear to be in the right place and at the right time in your life? In reality, it could be a combination of everything. Interestingly, regardless of the end goal - whether it is dancing or robbery - the mechanisms underlying these social connections have remarkable similarities.**

## Criminals and criminal networks

When we use the term “criminal” or “offender” we refer to a person who breaks the laws and rules of a given country. Some crimes can be performed by one person, for instance, tax fraud. However, some criminal acts can be more sophisticated and require collaboration between several people. For example, as criminal literature shows, burglary has the highest prevalence of co-offending. It is believed that criminals also form social networks, which we call “criminal networks”. These networks can serve as a pool of potential partners and collaborations. 

<center><iframe src="https://giphy.com/embed/3o6gbchrcNIt4Ma8Tu" width="480" height="270" frameBorder="0" class="giphy-embed"></iframe></center>

Suppose someone is seeking a partner to rob a house. What qualities would be the most important in a potential partner? To answer this question, let's take a look at business partnerships. Production companies are always trying to develop new solutions and products. However, sometimes this cannot be achieved internally, so they seek the help of external companies. For example, a leading electronics corporation, Samsung wouldn’t simply partner with a skin-care brand like Nivea to design an improved camera for its upcoming smartphone line. Instead, Samsung would most likely collaborate with a trustworthy company that is qualified for this specific task of camera design and importantly is willing to collaborate. When it comes to robbery, criminals are more likely to team up with someone who has relevant experience, can be trusted not to betray them, and is currently available.

## It's not what you know but who you know

Our social networks can comprise a myriad of individuals, but we can't afford equal time and attention to all of them. We tend to interact more frequently with a select few, termed "strong ties," which are akin to close friendships. Simultaneously, we maintain "weak ties" with people we see less often, who nevertheless play a valuable role in our network.

[In 1973 Granovetter has shown](https://www.jstor.org/stable/2776392) that we, humans, oftentimes rely on weak ties in our social networks. People have reported finding new jobs on LinkedIn through people they barely know and in general, novel information might diffuse faster through the weak ties in the online social websites. This might feel counterintuitive, but there is a rationale behind it. If you have a small but very connected group of people you interact with daily, you are likely exposed to the same information and opportunities and there is no room for exploring new things. And if you are looking for a new job, all your close professional contacts are more likely to have the same options in mind as you have already tried. However, a random post with a vacancy ad on LinkedIn from a person you barely know might open a door for new opportunities.

It is believed that criminals might experience the same when it comes to a criminal partner selection. [Tremblay has suggested](http://dx.doi.org/10.4324/9781315128788-2) that offenders might use both types of ties, strong and weak. Using this approach criminals interact with strong ties that are defined by the high level of trust to commit crimes together, but at the same time, they also rely on weak ties for accessing new skills and information. However, some criminals might prefer only strong ties since collaboration with them has a higher chance of success and fewer chances of betrayal.

## Right place, right time?

However, are humans always guided by rational calculations when forming new connections? Do we write down all the pros and cons of a person we want to go on a first date with and perform a thorough risk-benefit analysis? Sometimes, individuals enter our lives spontaneously and become good friends of ours or we share a significant event with them. For instance, a casual encounter in a hostel bar might lead to an unforgettable scuba diving adventure.

In her work, ["Robbery arising out of a group drinking-context"](https://scholar.google.com/scholar_lookup?title=Robbery%20arising%20out%20of%20a%20group%20drinking%20context&publication_year=1986&author=A.T.%20Cordilia), Ann Teresa Cordilia has shown that some criminal events happen on the spur of the moment. She has discussed how group drinking situations might give rise to casual robbery. Here is a quote from one of the interviews:

> G. L. and R. were drinking and were “half crocked”. S. said he knew about a car [which they could steal] which somebody wanted so they could get rid of it. G. had doubts because he didn’t want to violate his parole. But he went along anyway and that’s how he ended up [in prison], (Cordilia, 1983)

<center><iframe src="https://giphy.com/embed/fjxbfQKLcKzAJIqSuD" width="480" height="270" frameBorder="0" class="giphy-embed"></iframe></center>

[Marcus Felson has formulated](https://scholar.google.com/scholar_lookup?&title=The%20process%20of%20co-offending&journal=Crime%20Prev%20Stud&volume=16&pages=149-167&publication_year=2003&author=Felson%2CM) three requirements for a successful co-offense: (1) co-offenders must physically gather at the same place and time; (2) they should be able to communicate with each other without outside interference; and (3) they need enough time to socialize.

## People like people like them

We have already explored possible motivations and causes for collaboration among people. However, something must attract us to these individuals and prompt us to create a connection. Consider your friends and the common interests and opinions you share. Do you find that your friends share your worldview or do you have vastly different views? Chances are, you are probably very similar to your friends in some areas, such as musical preferences, religious beliefs, or shared sports activities.

In her [blog post](https://www.psychologytoday.com/intl/blog/close-encounters/201812/why-do-we-people-who-are-similar-us) Gwendolyn Seidman discusses why we might tend to like people who have or are perceived to have similar interests as us. There are several possible explanations for this phenomenon. For instance, when we see someone who has similar attitudes toward the world, we become more confident that our own attitudes are appreciated and correct. Another possible explanation is that we believe that people who have a lot in common with us are more likely to like us in return.

Unfortunately, it is not always straightforward to assess how similar or dissimilar criminal partners are in terms of interests, political views, or religion. What we do know, however, is that criminal groups most often tend to be homophilous in terms of age and sex, meaning that someone would rather co-offend with someone who is the same sex and around the same age as them. [Analyzing the survey data](
https://doi.org/10.1177/1043463113512996) from US schools, Flashman and Gambetta found that adolescents who participate in illicit activities prefer similar friends even more than those who participate in licit activities.

Moreover, [Granovetter proposed](https://www.jstor.org/stable/2776392) a theory of triadic closure, which can be seen as a byproduct of homophily. In simple terms, theory suggests that if you have two friends who are similar to you, but they don’t know each other yet, they are very likely to be similar as well and become friends as well. This social phenomenon has been replicated in studies of co-offending groups, showing that criminals are more likely to co-offend with the partner of their previous partners. In fact, [Alberto Nieto and colleagues have shown](https://doi.org/10.1007/s41109-023-00531-0) that it is even more likely to collaborate with the partner of your previous partner than to choose a "popular" criminal or collaborate with the same person as before.

## Closing remarks

Studying social criminal behavior is a crucial yet challenging task. Understanding how offenders find partners can assist law enforcement in preventing future collaborations and ensuring a safer society. However, it's essential to remember that every crime has its consequences, and it's far wiser to enjoy the company of friends in a bar than to end up behind bars.